package com.schoolmgmt.app.utils

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color as AndroidColor
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.widget.Toast
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream

object ReceiptPdfHelper {

    fun generateAndShareInvoicePdf(
        context: Context,
        schoolName: String,
        receiptNo: String,
        dateStr: String,
        studentName: String,
        admissionNo: String,
        className: String,
        particulars: String,
        paidAmount: Double,
        mode: String,
        remainingDues: Double,
    ) {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val paint = Paint().apply {
            color = AndroidColor.BLACK
            isAntiAlias = true
        }

        var y = 60f
        val width = 595

        // School Title
        paint.apply {
            textSize = 28f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText(schoolName.uppercase(), (width / 2).toFloat(), y, paint)

        y += 35f
        paint.apply {
            textSize = 18f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        }
        canvas.drawText("OFFICIAL PAYMENT RECEIPT", (width / 2).toFloat(), y, paint)

        y += 30f
        paint.textAlign = Paint.Align.LEFT
        canvas.drawText("--------------------------------------------------------------------------", 20f, y, paint)

        // Metadata block
        y += 30f
        paint.textSize = 15f
        canvas.drawText("Receipt No: $receiptNo", 40f, y, paint)
        canvas.drawText("Date: $dateStr", 380f, y, paint)

        y += 25f
        canvas.drawText("Student Name: $studentName", 40f, y, paint)
        canvas.drawText("Admission No: $admissionNo", 380f, y, paint)

        y += 25f
        canvas.drawText("Class: $className", 40f, y, paint)

        y += 30f
        canvas.drawText("--------------------------------------------------------------------------", 20f, y, paint)

        // Columns header
        y += 30f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Particulars", 40f, y, paint)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText("Amount", 550f, y, paint)

        y += 25f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        paint.textAlign = Paint.Align.LEFT
        canvas.drawText("--------------------------------------------------------------------------", 20f, y, paint)

        // Particulars list
        y += 35f
        canvas.drawText(particulars, 40f, y, paint)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText("₹${"%.2f".format(paidAmount)}", 550f, y, paint)

        y += 35f
        paint.textAlign = Paint.Align.LEFT
        canvas.drawText("--------------------------------------------------------------------------", 20f, y, paint)

        // Totals summary
        y += 35f
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Total Paid (${mode}):", 40f, y, paint)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText("₹${"%.2f".format(paidAmount)}", 550f, y, paint)

        y += 30f
        paint.textAlign = Paint.Align.LEFT
        canvas.drawText("Outstanding Dues Balance:", 40f, y, paint)
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText("₹${"%.2f".format(remainingDues)}", 550f, y, paint)

        y += 30f
        paint.textAlign = Paint.Align.LEFT
        canvas.drawText("--------------------------------------------------------------------------", 20f, y, paint)

        // Footer note
        y += 50f
        paint.apply {
            textSize = 14f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.ITALIC)
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText("This is an official cloud-synced receipt generated by the school app.", (width / 2).toFloat(), y, paint)
        y += 20f
        canvas.drawText("Thank you for your payment!", (width / 2).toFloat(), y, paint)

        pdfDocument.finishPage(page)

        // Save PDF to cache
        val pdfFile = File(context.cacheDir, "receipt_${receiptNo}.pdf")
        try {
            FileOutputStream(pdfFile).use { out ->
                pdfDocument.writeTo(out)
            }
        } catch (e: Exception) {
            e.printStackTrace()
        } finally {
            pdfDocument.close()
        }

        // Trigger Android Share Intent
        try {
            val authority = "${context.packageName}.fileprovider"
            val uri = FileProvider.getUriForFile(context, authority, pdfFile)
            
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(shareIntent, "Share Invoice PDF"))
        } catch (e: Exception) {
            Toast.makeText(context, "Error sharing receipt PDF: ${e.message}", Toast.LENGTH_LONG).show()
        }
    }
}
